### ISSUE TITLE
tunnel-ssh-client: Fails to create config on target machine

### ISSUE THREAD

**Issue by pixlblur-** [leesoh/yams#13]
When creating the config file for tunnel-ssh-client, config file fails to copy over to /.ssh/config if there is no /.ssh/ folder currently present.   It does work if the /.ssh/ folder already exists.

TASK [tunnel-ssh-client : Create ssh config] *********************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 2] No such file or directory
fatal: [xubuntutest]: FAILED! => {"changed": false, "failed": true, "msg": "Could not replace file: /tmp/tmpe6qCRY to /home/test/.ssh/config: [Errno 2
] No such file or directory"}

**Comment by leesoh** [comment]
Fixed in #14
